name: Fallow analysis
on:
  workflow_call:

jobs:
  fallow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Fallow Analysis
        uses: fallow-rs/fallow@v2
        with:
          format: sarif